# Generated by Django 2.2.9 on 2020-03-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometuitionsystemapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=10)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='teacher')),
                ('education', models.CharField(max_length=50)),
                ('slc_marksheet', models.FileField(upload_to='slc')),
                ('plus2_transcript', models.FileField(upload_to='plus2')),
                ('bachelor_marksheet', models.FileField(upload_to='bachelor')),
                ('cv', models.FileField(upload_to='cv')),
                ('about', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
